require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Admin::FellowOpportunitiesController, type: :controller do
  render_views
  
  let(:user) { create :admin_user }

  # This should return the minimal set of attributes required to create a valid
  # FellowOpportunity. As you add validations to FellowOpportunity, be sure to
  # adjust the attributes here as well.
  let(:fellow) { build :fellow, id: 1001 }
  let(:opportunity) { build :opportunity, id: 1002 }
  let(:opportunity_stage) { build :opportunity_stage, id: 1003 }
  
  let(:valid_attributes) { attributes_for :fellow_opportunity, fellow_id: fellow.id, opportunity_id: opportunity.id, opportunity_stage_id: opportunity_stage.id }
  let(:invalid_attributes) { {fellow_id: ''} }
  
  before do
    sign_in user

    allow_any_instance_of(FellowOpportunity).to receive(:fellow).and_return(fellow)
    allow_any_instance_of(FellowOpportunity).to receive(:opportunity).and_return(opportunity)
    allow_any_instance_of(FellowOpportunity).to receive(:opportunity_stage).and_return(opportunity_stage)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FellowOpportunitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'when signed-in user is not admin' do
    let(:user) { create :fellow_user }

    it "redirects GET #index to home" do
      get :index, params: {}, session: valid_session
      expect(response).to redirect_to(root_path)
    end
    
    it "redirects GET #show to home" do
      get :show, params: {id: '1001'}, session: valid_session
      expect(response).to redirect_to(root_path)
    end

    it "redirects GET #new to home" do
      get :new, params: {}, session: valid_session
      expect(response).to redirect_to(root_path)
    end
    
    it "redirects GET #edit to home" do
      get :edit, params: {id: '1001'}, session: valid_session
      expect(response).to redirect_to(root_path)
    end
    
    it "redirects POST #create to home" do
      post :create, params: {fellow_opportunity: valid_attributes}, session: valid_session
      expect(response).to redirect_to(root_path)
    end
    
    it "redirects PUT #update to home" do
      put :update, params: {id: '1001', fellow_opportunity: valid_attributes}, session: valid_session
      expect(response).to redirect_to(root_path)
    end
    
    it "redirects DELETE #destroy to home" do
      delete :destroy, params: {id: '1001'}, session: valid_session
      expect(response).to redirect_to(root_path)
    end
  end

  describe "GET #index" do
    it "returns a success response" do
      fellow_opportunity = FellowOpportunity.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      fellow_opportunity = FellowOpportunity.create! valid_attributes
      get :show, params: {id: fellow_opportunity.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      fellow_opportunity = FellowOpportunity.create! valid_attributes
      get :edit, params: {id: fellow_opportunity.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FellowOpportunity" do
        expect {
          post :create, params: {fellow_opportunity: valid_attributes}, session: valid_session
        }.to change(FellowOpportunity, :count).by(1)
      end

      it "redirects to the created fellow_opportunity" do
        post :create, params: {fellow_opportunity: valid_attributes}, session: valid_session
        expect(response).to redirect_to(admin_fellow_opportunity_path(FellowOpportunity.last))
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {fellow_opportunity: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_staff_notes) { valid_attributes[:staff_notes].to_s + ' 2' }
      let(:new_attributes) { {staff_notes: new_staff_notes} }

      it "updates the requested fellow_opportunity" do
        fellow_opportunity = FellowOpportunity.create! valid_attributes
        put :update, params: {id: fellow_opportunity.to_param, fellow_opportunity: new_attributes}, session: valid_session
        fellow_opportunity.reload
        
        expect(fellow_opportunity.staff_notes).to eq(new_staff_notes)
      end

      it "redirects to the fellow_opportunity" do
        fellow_opportunity = FellowOpportunity.create! valid_attributes
        put :update, params: {id: fellow_opportunity.to_param, fellow_opportunity: valid_attributes}, session: valid_session
        expect(response).to redirect_to(admin_fellow_opportunity_path(fellow_opportunity))
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        fellow_opportunity = FellowOpportunity.create! valid_attributes
        put :update, params: {id: fellow_opportunity.to_param, fellow_opportunity: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested fellow_opportunity" do
      fellow_opportunity = FellowOpportunity.create! valid_attributes
      expect {
        delete :destroy, params: {id: fellow_opportunity.to_param}, session: valid_session
      }.to change(FellowOpportunity, :count).by(-1)
    end

    it "redirects to the fellow_opportunities list" do
      fellow_opportunity = FellowOpportunity.create! valid_attributes
      delete :destroy, params: {id: fellow_opportunity.to_param}, session: valid_session
      expect(response).to redirect_to(admin_fellow_opportunities_url)
    end
  end

end
