-
  name: strengths
  description: "I know my strengths and values and can communicate my story"
-
  name: accelerating
  description: "I understand what career-accelerating means and what career paths can look like"
-
  name: roadmap
  description: "I have a career roadmap with professional goals and a plan"
-
  name: resume
  description: "My resume is strong and ready to send to potential employers"
-
  name: linkedin
  description: "My LinkedIn profile is updated and professional"
-
  name: social media
  description: "My social media is scrubbed of content I don’t want potential employers to see"
-
  name: elevator pitch
  description: "I know my elevator pitch like the back of my hand"
-
  name: networking
  description: "I have a networking strategy and a system for keeping track of opportunities and people I meet"
-
  name: interviews
  description: "I’ve had informational interviews with professionals in my desired career field"
-
  name: ready
  description: "I am ready to ace a job interview"
-
  name: reflection
  description: "I've reflected on what I want to look for next and researched the field"
-
  name: employers
  description: "I've made a shortlist of positions and/or employers"