"Agriculture & Natural Resources":
  - "Agricultural Economics"
  - "Agriculture"
  - "Agriculture Production And Management"
  - "Food Science"
  - "Forestry"
  - "General Agriculture"
  - "Natural Resources Management"
  - "Plant Science And Agronomy"
  - "Soil Science"
"Arts":
  - "Architecture"
  - "Drama And Theater Arts"
  - "Film"
  - "Fine Arts"
  - "Graphic Design"
  - "Music"
  - "Photography"
  - "Studio Arts"
  - "Visual And Performing Arts"
"Biology & Life Science":
  - "Biochemical Sciences"
  - "Biology"
  - "Botany"
  - "Cognitive Science"
  - "Ecology"
  - "Environmental Science"
  - "Forensic Science"
  - "Genetics"
  - "Microbiology"
  - "Molecular Biology"
  - "Neuroscience"
  - "Pharmacology"
  - "Physiology"
  - "Zoology"
"Business":
  - "Accounting"
  - "Actuarial Science"
  - "Business Analytics"
  - "Business Economics"
  - "Business Management And Administration"
  - "Entrepreneurship"
  - "Finance"
  - "General Business"
  - "Hospitality Management"
  - "Human Resources"
  - "International Business"
  - "Management Information Systems"
  - "Marketing"
  - "Operations Logistics"
  - "Supply Chain Management"
"Communications & Journalism":
  - "Advertising"
  - "Communications"
  - "Journalism"
  - "Mass Media"
  - "Public Relations"
"Computer Science & Software Engineering":
  - "Communication Technologies"
  - "Computer Administration Management And Security"
  - "Computer And Information Systems"
  - "Computer Engineering"
  - "Computer Networking"
  - "Computer Programming And Data Processing"
  - "Computer Science"
  - "Information Sciences"
  - "Software Engineering"
  - "Telecommunications"
"Education":
  - "Art And Music Education"
  - "Early Childhood Education"
  - "Educational Administration"
  - "Elementary Education"
  - "Foreign Language Education"
  - "General Education"
  - "Library Science"
  - "Mathematics Teacher Education"
  - "Miscellaneous Education"
  - "Physical Education Teaching"
  - "School Student Counseling"
  - "Science Teacher Education"
  - "Secondary Teacher Education"
  - "Social Science Or History Teacher Education"
  - "Special Needs Education"
  - "Teacher Education: Multiple Levels"
"Engineering":
  - "Aerospace Engineering"
  - "Architectural Engineering"
  - "Biological Engineering"
  - "Biomedical Engineering"
  - "Chemical Engineering"
  - "Civil Engineering"
  - "Electrical Engineering"
  - "Electrical Engineering Technology"
  - "Engineering And Industrial Management"
  - "Engineering Mechanics Physics And Science"
  - "Engineering Technologies"
  - "Environmental Engineering"
  - "General Engineering"
  - "Geological And Geophysical Engineering"
  - "Industrial And Manufacturing Engineering"
  - "Industrial Production Technologies"
  - "Materials Engineering And Materials Science"
  - "Materials Science"
  - "Mechanical Engineering"
  - "Metallurgical Engineering"
  - "Mining And Mineral Engineering"
  - "Miscellaneous Engineering"
  - "Naval Architecture And Marine Engineering"
  - "Nuclear Engineering"
  - "Petroleum Engineering"
"Government":
  - "Public Administration"
  - "Public Policy"
"Health":
  - "Animal Sciences"
  - "Communication Disorders Sciences And Services"
  - "General Medical And Health Services"
  - "Health And Medical Administrative Services"
  - "Health Sciences"
  - "Kinesiology"
  - "Medical Assisting Services"
  - "Medical Technologies Technicians"
  - "Nursing"
  - "Nutrition Sciences"
  - "Pharmaceutical Sciences And Administration"
  - "Pre-Med"
  - "Public Health"
  - "Treatment Therapy Professions"
"Humanities":
  - "Anthropology"
  - "Arabic"
  - "Art History"
  - "Chinese"
  - "Classics"
  - "Composition And Rhetoric"
  - "English Language And Literature"
  - "Ethnic Studies"
  - "French"
  - "German"
  - "History"
  - "Humanities"
  - "International Studies"
  - "Italian"
  - "Japanese"
  - "Liberal Arts"
  - "Linguistics"
  - "Other Foreign Languages"
  - "Philosophy"
  - "Religion"
  - "Russian"
  - "Spanish"
  - "Theology"
  - "United States History"
  - "Women and Gender Studies"
"Industrial Arts & Consumer Services":
  - "Construction Services"
  - "Consumer Sciences"
  - "Cosmetology Services"
  - "Culinary Arts"
  - "Electrical, Mechanical, And Precision Technologies And Production"
  - "Military Technologies"
  - "Physical Fitness Parks Recreation And Leisure"
  - "Transportation Sciences And Technologies"
"Interdisciplinary":
  - "Multi/Interdisciplinary Studies"
"Law":
  - "Court Reporting"
  - "Pre-Law"
"Mathematics":
  - "Applied Mathematics"
  - "Mathematics"
  - "Statistics"
"Physical Sciences":
  - "Astronomy And Astrophysics"
  - "Atmospheric Sciences And Meteorology"
  - "Chemistry"
  - "Geology And Earth Science"
  - "Geosciences"
  - "Multi-Disciplinary Or General Science"
  - "Nuclear, Industrial Radiology, And Biological Technologies"
  - "Oceanography"
  - "Physical Sciences"
  - "Physics"
"Psychology & Social Services":
  - "Clinical Psychology"
  - "Community Organizing"
  - "Counseling Psychology"
  - "Criminal Justice"
  - "Educational Psychology"
  - "Human Services"
  - "Industrial And Organizational Psychology"
  - "Miscellaneous Psychology"
  - "Psychology"
  - "Social Psychology"
  - "Social Work"
"Social Science":
  - "Criminology"
  - "Economics"
  - "General Social Sciences"
  - "Geography"
  - "Government"
  - "Interdisciplinary Social Sciences"
  - "International Relations"
  - "Political Science"
  - "Sociology"
  - "Urban Studies"
"Undeclared":