default links: &default_links
  next: "Yes"
  no change: "Not Yet"
  skip: "Does Not Apply"
  fellow declined: "No Longer Interested"
    
default links with employer: &default_links_with_employer
  <<: *default_links
  employer declined: "Employer Declined"
  
default notices: &default_notices
  next: "Okay, thanks for the update, <%= @fellow.first_name %>. Here’s the next recommended step:"
  skip: "Okay, thanks for the update, <%= @fellow.first_name %>. Here’s the next recommended step:"
  no change: "Okay, <%= \"block out #{@content[@candidate.stage]['burden']} on your calendar to do this\" if @content[@candidate.stage]['burden'] %> but don’t let it drag on too long. You’ll get another reminder soon!"
  fellow declined: "Sorry to hear it wasn't a good fit. Keep looking, we're sure you'll find something that works out!"
  employer declined: "Sorry to hear it wasn't a good fit. Keep looking, we're sure you'll find something that works out!"

respond to invitation:
  notices: *default_notices
    
research employer:
  phase: "Apply"
  title: "Research <%= @opportunity.employer.name %>"
  phase_position: 1
  question: "Have you researched <%= @opportunity.employer.name %> online?"
  tips:
    header: "Look up the employer's own website (see link above) and on other sites such as:"
    list:
      - "<%= link_to 'LinkedIn', 'https://www.linkedin.com', target: '_blank' %>"
      - "<%= link_to 'GlassDoor', 'https://www.glassdoor.com', target: '_blank' %>"
      - "<%= link_to 'Better Business Bureau', 'https://www.bbb.org', target: '_blank' %>"
      - "<%= link_to 'Idealist.org (for mission-driven organizations)', 'https://www.idealist.org', target: '_blank' %>"
  links: *default_links
  notices: *default_notices
  burden: "15 minutes"

connect with employees:
  phase: "Apply"
  title: "Connect with Current Employees"
  phase_position: 2
  question: "Have you networked and talked to people who work(ed) for <%= @opportunity.employer.name %>?"
  tips:
    list:
      - "Use your LinkedIn and Facebook connections to reach out to people who work(ed) at <%= @opportunity.employer.name %>."
      - "If you can't find any connections you can try to reach out directly through LinkedIn to someone who works there now. You have absolutely nothing to lose and it's very easy to do!"
      - "Introduce yourself, attach a resume, and ask them: \"What is it like to work there? What does the interview look like? Do you think I'll be a good fit for the company and the role?\""
      - "If it sounds like you're a good fit, ask for a referral: \"Would you be willing to refer me internally?\""
      - "This step doesn't take a lot of effort but it does take time. We'll send you helpful reminders about it so you stay on track."
      - "PRO TIP: Keep taking feedback and revise your application materials accordingly."
  links: *default_links
  notices: *default_notices
  burden: "an hour"

customize application materials:
  phase: "Apply"
  title: "Customize Your Application Materials"
  phase_position: 3
  question: "Have you customized your resume, cover Letter, and other materials for this opportunity (eg, portfolio)?"
  tips:
    header: "More Info:"
    list:
      - "Highlight the skills and experiences you have that best match the jobs and companies you're interested in."
      - "Keep revising based on feedback from your campus career center, Braven Fellows and your Coach, and anyone else who could help."
      - "Search for yourself online as an employer might do, and adapt all your profiles to look professional and relevant."
      - "Follow key companies and people in the industry, and join relevant groups and meetups."
      - "PRO TIP: Catch all the typos! Professional polish shows that you care about doing your job well."
  links: *default_links
  notices: *default_notices
  burden: "30 minutes"
    
submit application:
  phase: "Apply"
  title: "Submit Your Application"
  phase_position: 4
  question: "Have you submitted your application to <%= @opportunity.employer.name %>?"
  tips:
    list:
      - "Make sure your resume and cover letter are in the appropriate format (PDF unless they ask for something else)."
      - "You don't need special software; just search online for \"how to print to PDF on [Windows/Mac/Linux]\""
      - "If you're emailing the application be sure to include a short note thanking the hiring manager for the opportunity to apply."
  links: *default_links
  notices: *default_notices
  burden: "5-15 minutes"
      
follow up after application:
  phase: "Apply"
  title: "Follow Up on Your Application"
  phase_position: 5
  question: "Have you followed up to see your application through?"
  tips:
    header: "Follow up with any contacts you have who might have some influence at the company (e.g. current and past employees, partners, clients) by sending them a copy of the resume and cover letter and asking \"Would you be willing to put in a word for me to make sure my application is considered?\""
  links: *default_links_with_employer
  notices: *default_notices
  burden: "5 minutes"

schedule interview:
  phase: "Interview"
  title: "Schedule an Interview"
  phase_position: 1
  question: "Have you scheduled an interview?"
  links: *default_links_with_employer
  notices: *default_notices
  
research interview process:
  phase: "Interview"
  title: "Research <%= @opportunity.employer.name %>'s interview Process"
  phase_position: 2
  question: "Have you researched the interview process at <%= @opportunity.employer.name %>?"
  tips:
    list:
      - "Look through the job posting and anything else you've gotten from this employer so far for info on how the interview process works."
      - "Use online search, social media (including LinkedIn) and your network: What is the life story of the hiring manager(s) / interviewer(s)? Where did they go to school and what did they study? Do they have a blog or published work online or in print? If so, what are their interests and opinions? Were they mentioned in news stories? Are they active on online forums?"
      - "Brainstorm what questions they might ask based on what you've learned about them."
      - "PRO TIP: Research what people wear on the actual job so you can dress appropriately for your interview."
  links: *default_links
  notices: *default_notices

practice for interview:
  phase: "Interview"
  title: "Practice for Your Interview"
  phase_position: 3
  question: "Have you practiced for your interview with <%= @opportunity.employer.name %>?"
  tips:
    list:
      - "Brainstorm possible questions they may ask and write out your answers (can be in bullet points)."
      - "Prepare some stories you can use: have several stories using the PAR and SYRCL frameworks."
      - "Prepare 3-5 questions you can ask your interviewer."
      - "Practice with people you know in the field, your campus career center, other Fellows, your Coach, or even friends and family."
  links: *default_links
  notices: *default_notices

attend interview:
  phase: "Interview"
  title: "Ace Your Interview!"
  phase_position: 4
  question: "Have you attended your interview with <%= @opportunity.employer.name %> yet?"
  tips:
    list:
      - "Make a great first impression: dress to impress (match the employer's dress code), arrive 10 minutes early, and be kind and courteous (e.g. turn off your phone)."
      - "If it's a phone or virtual interview: find a quiet place with a good signal and be ready 10 minutes ahead of time."
      - "Reserve some free time after the interview in case it starts late or goes longer than expected."
      - "PRO TIP: Bring copies of your resume and some business cards."
  links: *default_links
  notices: *default_notices

follow up after interview:
  phase: "Interview"
  title: "Follow Up After Your Interview"
  phase_position: 5
  question: "Have you followed up after your interview with <%= @opportunity.employer.name %>?"
  tips:
    header: "Send a quick follow up to express your continued excitement for the opportunity and to follow-up on anything from the interview."
  links: *default_links_with_employer
  notices: *default_notices
  
receive offer:
  phase: "Offer"
  title: "Look out for an Offer"
  phase_position: 1
  question: "Have you received an offer from <%= @opportunity.employer.name %> yet?"
  links:
    next: "Yes"
    no change: "Not Yet"
    fellow declined: "No Longer Interested"
    employer declined: "Employer Declined"
  notices: *default_notices

submit counter-offer:
  phase: "Offer"
  title: "Consider making a Counter Offer"
  phase_position: 2
  question: "Have you submitted a counter offer to <%= @opportunity.employer.name %>?"
  tips:
    list:
      - "Give yourself a pat on the back and celebrate! You've made it this far, regardless of whether you'll end up agreeing on the terms."
      - "Get advice on negotiating your salary and benefits package: Consult mentors and other people in your network, as well as sites like glassdoor.com and the Bureau of Labor Statistics to assess the offer you received."
      - "PRO TIP: The offer you get won't always be a fair one. If it's too low (based on your research), propose a counter-offer that's a little better than you'd expect to end up with and let them counter it."
  links:
    receive offer: "Submitted Counter-Offer"
    no change: "Not Yet"
    fellow accepted: "Accepted Offer"
    fellow declined: "No Longer Interested"
  notices:
    <<: *default_notices
    receive offer: "Way to Go!"
    fellow accepted: "Congratulations!"

accept offer:
  phase: "Offer"
  title: "Accept Your Offer!"
  phase_position: 3
  question: "Have you accepted the offer you got from <%= @opportunity.employer.name %>?"
  links: *default_links
  notices:
    <<: *default_notices
    next: "Congratulations!"