development:
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  root_domain: <%= ENV['ROOT_DOMAIN'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  # No emails are actually sent from the test server, but
  # it does need a to email lest it throws "invalid smtp email" exceptions
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  nlu_sso_url: <%= ENV['NLU_SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>
  calendly_magic_token: <%= ENV['CALENDLY_MAGIC_TOKEN'] %>
  cookie_domain: <%= ENV['COOKIE_DOMAIN'] %>
  google_spreadsheet_client_id: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_ID'] %>
  google_spreadsheet_client_secret: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_SECRET'] %>
  google_spreadsheet_refresh_token: <%= ENV['GOOGLE_SPREADSHEET_REFRESH_TOKEN'] %>
  qa_host: <%= ENV['QA_HOST'] %>
  qa_token: <%= ENV['QA_TOKEN'] %>
  mailchimp_key: <%= ENV['MAILCHIMP_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_production_list_id: <%= ENV['MAILCHIMP_PRODUCTION_LIST_ID'] %>
  test_sso_username: <%= ENV['TEST_SSO_USERNAME'] %>
  test_sso_password: <%= ENV['TEST_SSO_PASSWORD'] %>
  redis_url: <%= ENV['DEV_REDIS_URL'] %>
  mailer_bcc: <%= ENV['MAILER_BCC'] %>

test:
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  root_domain: <%= ENV['ROOT_DOMAIN'] %>
  mailer_from_email: 'test@localhost'
  # No emails are actually sent from the test server, but
  # it does need a to email lest it throws "invalid smtp email" exceptions
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: '12312321322'
  devise_secret_key: '12312312312'
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  nlu_sso_url: <%= ENV['NLU_SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>
  calendly_magic_token: <%= ENV['CALENDLY_MAGIC_TOKEN'] %>
  cookie_domain: <%= ENV['COOKIE_DOMAIN'] %>
  google_spreadsheet_client_id: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_ID'] %>
  google_spreadsheet_client_secret: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_SECRET'] %>
  google_spreadsheet_refresh_token: <%= ENV['GOOGLE_SPREADSHEET_REFRESH_TOKEN'] %>
  qa_host: <%= ENV['QA_HOST'] %>
  qa_token: <%= ENV['QA_TOKEN'] %>
  mailchimp_key: <%= ENV['MAILCHIMP_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_production_list_id: <%= ENV['MAILCHIMP_PRODUCTION_LIST_ID'] %>
  test_sso_username: <%= ENV['TEST_SSO_USERNAME'] %>
  test_sso_password: <%= ENV['TEST_SSO_PASSWORD'] %>
  redis_url: <%= ENV['TEST_REDIS_URL'] %>
  mailer_bcc: <%= ENV['MAILER_BCC'] %>

staging:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  root_domain: <%= ENV['ROOT_DOMAIN'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  # No emails are actually sent from the test server, but
  # it does need a to email lest it throws "invalid smtp email" exceptions
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>
  calendly_magic_token: <%= ENV['CALENDLY_MAGIC_TOKEN'] %>
  cookie_domain: <%= ENV['COOKIE_DOMAIN'] %>
  google_spreadsheet_client_id: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_ID'] %>
  google_spreadsheet_client_secret: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_SECRET'] %>
  google_spreadsheet_refresh_token: <%= ENV['GOOGLE_SPREADSHEET_REFRESH_TOKEN'] %>
  qa_host: <%= ENV['QA_HOST'] %>
  qa_token: <%= ENV['QA_TOKEN'] %>
  mailchimp_key: <%= ENV['MAILCHIMP_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_production_list_id: <%= ENV['MAILCHIMP_PRODUCTION_LIST_ID'] %>
  test_sso_username: <%= ENV['TEST_SSO_USERNAME'] %>
  test_sso_password: <%= ENV['TEST_SSO_PASSWORD'] %>
  mailer_bcc: <%= ENV['MAILER_BCC'] %>

production:
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  root_domain: <%= ENV['ROOT_DOMAIN'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  # Note: the database dot com env vars are NOT here because
  # they are managed automatically by the gem - the environment variable
  # needs to be present, but we don't explicitly use it in our code
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>
  calendly_magic_token: <%= ENV['CALENDLY_MAGIC_TOKEN'] %>
  cookie_domain: <%= ENV['COOKIE_DOMAIN'] %>
  google_spreadsheet_client_id: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_ID'] %>
  google_spreadsheet_client_secret: <%= ENV['GOOGLE_SPREADSHEET_CLIENT_SECRET'] %>
  google_spreadsheet_refresh_token: <%= ENV['GOOGLE_SPREADSHEET_REFRESH_TOKEN'] %>
  qa_host: <%= ENV['QA_HOST'] %>
  qa_token: <%= ENV['QA_TOKEN'] %>
  mailchimp_key: <%= ENV['MAILCHIMP_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_production_list_id: <%= ENV['MAILCHIMP_PRODUCTION_LIST_ID'] %>
  test_sso_username: <%= ENV['TEST_SSO_USERNAME'] %>
  test_sso_password: <%= ENV['TEST_SSO_PASSWORD'] %>
  mailer_bcc: <%= ENV['MAILER_BCC'] %>
